project:
  type: website
  output-dir: docs

website:
  title: "Week 2 AAI1001 Site"
  favicon: Sources/favicon.jfif
  navbar:
    logo: Sources/logo.jfif
    left:
      - href: index.qmd
        text: Home
      - Experiences.qmd
      - Reflection.qmd

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    embed-resources: true
    page-navigation: true
    link-external-newwindow: true

