---
title: "Royston's Quarto Introduction Website "
---

## Background

Hello, my name is Royston. I am an AAI student at SIT.<br> 
I am an enthusiastic and dedicated individual with a passion for technology and innovation. I am currently pursuing my studies in the field of Artificial Intelligence and am eager to learn and grow in this exciting domain. I am looking forward to learning more about this field as I explore the different kind of work I could potentially do after Graduation. I am currently exploring the idea of breaking into finance as I used to work at OCBC as a UAT Tester.

Enrich your homepage, which is index.qmd file, with either your short self-introduction, a photo, video, or something that best represents you. Rename the about page to other names, e.g., FYP Project or other project, and add content related to your final year project (or other project) prior to entering SIT. Add at least one more page with your preferred title and related content which could be anything you would like to share with others. Here are a few examples that may inspire you: Curriculum that you have taken is worth of sharing in your opinion. Learning Notes you have taken in the past and how they helped you. Hobbies you would like to share and how they are carried out. Travel Experience you have had and how they influenced you. Recipe of XXX: about your favorite dish and the cooking steps. Movie XXX: sharing of your favorite movie information and your feedback. You can choose from countless subjects that you have experienced for sharing. Add a Reflection page with the title “Reflection on the use of GenAI”. In this page, share your experience of using GenAI to help you accomplish the assessment. A few optional aspects for you to consider if you have no idea what to write: What is the GenAI tool you have used? Why did you choose it? How did the GenAI tool help you in completing the assessment (with examples)? What do you think are beneficial about the tool? What do you think are challenging about the tool? How do you think will GenAI tools assist you for your future study or work? Any other thoughts you would like to share.

```{r}
1 + 1
```
